Fix a crash, value can't be deserialized to Long (#1171)
The full stacktrace looks like this:

    app.cash.zipline.QuickJsException: 9007199254740992 can't be deserialized to Long due to a potential precision loss
        at JavaScript.captureStack(./kotlin-kotlin-stdlib.js:3207)
        at JavaScript.SerializationException_init_$Create$_0(./kotlinx-serialization-kotlinx-serialization-core.js:828)
        at JavaScript.<anonymous>(./kotlinx-serialization-kotlinx-serialization-json.js:6533)
        at ...
        at JavaScript.decodeSerializableValuePolymorphic(./kotlinx-serialization-kotlinx-serialization-json.js:2569)
        at JavaScript.<anonymous>(./kotlinx-serialization-kotlinx-serialization-json.js:6385)
        at JavaScript.decodeDynamic(./kotlinx-serialization-kotlinx-serialization-json.js:6252)
        at JavaScript.decodeFromDynamic(./kotlinx-serialization-kotlinx-serialization-json.js:6227)
        at JavaScript.decodeFromStringFast(./zipline-root-zipline.js:4221)
        at ...
        at app.cash.zipline.JniCallChannel.call(Native Method)
        at app.cash.zipline.JniCallChannel.call(JniCallChannel.kt:25)
        at app.cash.zipline.Zipline$endpoint$1.call(Zipline.kt:61)
        at app.cash.zipline.internal.bridge.OutboundCallHandler.call(OutboundCallHandler.kt:98)
        at app.cash.zipline.testing.EncodingService$Companion$Adapter$GeneratedOutboundService.echoLong(encoding.kt:20)
        at app.cash.zipline.EncodingTest$encodeLong$1.invokeSuspend(EncodingTest.kt:48)

The unfortunate consequence of this change is that longs must be
annotated @Contextual when they are used in the signatures of Zipline
functions and when they are used as field declarations of serializable
objects used with Zipline.