Upgrade to Kotlin 1.9.20 (#1158)
* Upgrade to Kotlin 1.9.20

* Track some changes in IR APIs

* cklib 0.3.0

* Patch quickjs.c to work around an error in Clang

    error: implicit conversion from 'long long' to 'double' changes
           value from 9223372036854775807 to 9223372036854775808
           [-Werror,-Wimplicit-const-int-float-conversion]
                    else if (d > INT64_MAX)
                               ~ ^~~~~~~~~

* Track a Fir API change in KotlinFirLoader

* Track JS module dependency changes

* apiDump

* Update kctfork

https://github.com/ZacSweers/kotlin-compile-testing/blob/main/CHANGELOG.md#040

* Use a pre-release Compose compiler with the WorldClock sample